<?php 
$theme = "default";
if (isset($_COOKIE["themeSetting"])) {
    $theme = $_COOKIE["themeSetting"];
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <title>RaspiControl</title>
    <link rel="icon" href="/resources/images/icons/logo.png" type="image/png" >
    <link rel="stylesheet" type="text/css" href="/resources/css/<?php echo $theme; ?>.css" >
    <script type="text/javascript" src="/resources/js/pageLoader.js" ></script>
    <script type="text/javascript" src="/resources/js/libs/myTools.js"></script>
    <script type="text/javascript" src="/resources/js/livingWeb/node.js"></script>
    <script type="text/javascript" src="/resources/js/livingWeb/livingWeb.js" defer></script>
</head>
<body>
<main>
    <canvas id="bgCanvas" ></canvas>
    <header>
        <img src="/resources/images/Banner.png" alt="Banner" id="banner" />
        <button onclick="nextTheme();" style='position: relative; bottom: 1.5rem; left: calc(100% - 8em); font-size: 0.7em;'>Switch Theme</button>
        <button id="lwToggle" onclick="toggleLivingWeb();">
            <img id="lwPlay" src="/resources/images/icons/play.png" alt="Play"/>
            <img id="lwPause" src="/resources/images/icons/pause.png" alt="Pause"/>
        </button>
    </header>
    <nav>
        <div id="stickynav">
            <button onclick="requestPage('/home.html')">
                <img src="/resources/images/icons/logo.png" alt="Logo" />
                Home <span></span>
            </button>

            <button onclick="
                requestPage('/monitoring.html');
                requestScript('/resources/js/external/chartjs/Chart.min.js');
                requestScript('/resources/js/monitoring.js');
                beginExecution('startRPICharts');
                ">
                <img src="/resources/images/icons/monitoring.png" alt="Monitoring"/>
                Monitor <span></span>
            </button>

            <!--<button onclick="
                requestPage('/watersystem.html');
                requestScript('/resources/js/external/chartjs/Chart.min.js');
                requestScript('/resources/js/waterSystem.js');
                ">
                <img src="/resources/images/icons/watersystem.png" alt="WaterSystem"/>
                W.S.C. <span></span>
            </button>-->

            <button onclick="
                requestPage('/notes.html');
                requestScript('/resources/js/external/showdown/showdown.min.js');
                requestScript('/resources/js/notes/notes.js');
                requestScript('/resources/js/notes/emojis.js');
                beginExecution('getNoteGroups');
            ">
                <img src="/resources/images/icons/notes.png" alt="Notes"/>
                Notes <span></span>
            </button>

            <button onclick="
                requestPage('/habits.html');
                requestScript('/resources/js/habits.js');
                beginExecution('getHabits');
            ">
                <img src="/resources/images/icons/habits.png" alt="Habits" />
                Habits <span></span>
            </button>

            <!--<button onclick="
                requestScript('/resources/js/external/napchart/napchart.min.js');
                requestPage('/napchart.html');
                requestScript('/resources/js/napchart.js');
                beginExecution('startNapChart');
            ">
                <img src="/resources/images/icons/napchart.png" alt="NapChart" />
                NapChart <span></span>
            </button>-->

            <button onclick="
            requestPage('/terminal.html');
            requestScript('/resources/js/terminal.js');
            beginExecution('getTerminalSrc')
">
                <img src="/resources/images/icons/bash.png" alt="bash">
                Terminal <span></span>
            </button>

            <button onclick="
            requestPage('/seafile.html');
            requestScript('/resources/js/seafile.js');
            beginExecution('getSeafileSrc')
">
                <img src="/resources/images/icons/seafile.png" alt="Seafile">
                Seafile <span></span>
            </button>

            <button onclick="
                requestPage('/users.html');
                requestScript('/resources/js/userManagement.js');
                beginExecution('getUserList');
                ">
                <img src="/resources/images/icons/user.png" alt="User Icon" />
                Users<span></span>
            </button>

            <button onclick="logout()">
                <img src="/resources/images/icons/logout.png" alt="Logout Icon" />
                Logout<span></span>
            </button>
        </div>
    </nav>
    <div id="main">
