@startuml

interface DCSocket #7f7
interface WSSocket #7f7
interface HTTP #8bf

node "Raspberry" #eee {
    database SQLite #6cf
    [WebServer] <-up- SQLite
    [DataCollector] -up-> SQLite
}

node "Controller" #eee {
    [ControlServer]
}

node "Sensor" #eee {
    [SensorServer]
}

node "ControlSensor" #eee {
    [ControlSensorServer]
}

node "Client" #eee {
    frame Browser #eff{
        [Page]
        [DataUpdater]
    }
}

DataCollector <--> DCSocket
DCSocket <--> SensorServer
DCSocket <--> ControlSensorServer

WebServer <--> WSSocket
WSSocket <--> ControlServer
WSSocket <--> ControlSensorServer

HTTP <.. DataUpdater
DataUpdater <- Page
DataUpdater -> Page
HTTP <-- Page
HTTP --> WebServer

@enduml